title: "Camille Chiu"
name: "Camille Chiu"
description: "Astrophysics at Yale"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache

author:
  name: "Camille Chiu"
  avatar: "/assets/portrait.jpg"
  bio: "Astrophysics at Yale"
  location: "New Haven, CT"
  email: "camille.chiu@yale.edu"
  github: "camchiu"
  linkedin: "https://www.linkedin.com/in/camille-chiu-580a3a1a9/"
